//FORM - ADD BORDERS TO THE FORM BOXES.  COLOUR THE SUBMIT BUTTON.  BUILD THE JAVASCRIPT FOR THE FORM (get the form entries to go to email address).//

//R.e. ENQUIRIES FORM, hAVE GOT SOME ADVICE ONLINE AND I THINK THAT IT MIGHT BE MORE USEABLE ON ELIZABETH'S END TO LINK TO MICROSOFT FORMS OR GOOGLE FORMS (Need to check if she can access these for free).  
THE OTHER OPTION IS TO FIND EXAMPLES OF PHP CODE ONLINE FOR SIMPLE ENQUIRY FORM AND CREATE VERSION OF THEM.//
//HAVE FOUND PHP TUTORIAL VIDEO ON https://www.bing.com/videos/riverview/relatedvideo?q=php+cod+for+email+contact+form&mid=C27C8A10F2527262B6D5C27C8A10F2527262B6D5&FORM=VIRE
WOULD HAVE TO MAKE FORM FAR MORE SIMPLE. BUT THIS SHOULD WORK.//

//ADD ELIZBETH COPYRIGH STATEMENT (OR LINK TO IT) IN FOOTER BAR.//
