
//HAVE FOUND PHP TUTORIAL VIDEO ON https://www.bing.com/videos/riverview/relatedvideo?q=php+cod+for+email+contact+form&mid=C27C8A10F2527262B6D5C27C8A10F2527262B6D5&FORM=VIRE
//HAVE USED ABOVE PHP TUTORIAL VIDEO AS A TEMPLATE FOR MY OWN PHP CODE.  FORM NOT 
CURRENTLY WORKING - GOING TO POST ON STACK OVERFLOW FOR ADVICE.
RECOMMEND TO ELIZABETH THAT SHE INSTEAD USES SOMETHING LIKE MICROSOFT FORMS.
BUT DOING IT USING PHP HAS BEEN A USEFUL TEST FOR MY SKILLS.//
